/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.NewHibernateUtil;
import javax.swing.JOptionPane;
import controlador.operaciones;
import java.awt.event.ItemEvent;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import modelo.Tematica;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import modelo.*;

/**
 *
 * @author pablo
 */
public class ventana_inscripcion extends javax.swing.JFrame {

    /**
     * Creates new form ventana_inscripcion
     */
    operaciones oper;
    List<Tematica> listaTematica;
    Participante aux = null;
    
    public ventana_inscripcion() {
        initComponents();
        setLocationRelativeTo(null);
        llenarTematicas();
        limpiarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionRegistrado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        registrado = new javax.swing.JRadioButton();
        noRegistrado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        buscarMail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tematicas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Inscripción");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiante"));

        opcionRegistrado.add(registrado);
        registrado.setText("Estudiante Registrado");
        registrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registradoMouseClicked(evt);
            }
        });

        opcionRegistrado.add(noRegistrado);
        noRegistrado.setText("Estudiante No Registrado");
        noRegistrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noRegistradoMouseClicked(evt);
            }
        });

        jLabel1.setText("Ingrese su e-mail: ");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Apellido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registrado)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addComponent(noRegistrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buscarMail, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jLabel2))
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(270, 270, 270))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrado)
                    .addComponent(jLabel1)
                    .addComponent(buscarMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noRegistrado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Vigentes"));

        tematicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tematicas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tematicasItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Profesor", "Aula", "Duración", "Carga Horaria", "Cupo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Inscribirse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tematicas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tematicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void llenarTematicas(){
        
        listaTematica = oper.tematicaVer();
        tematicas.removeAllItems();
        tematicas.addItem("Seleccione Tematica");
        for (Tematica tem : listaTematica) {
                tematicas.addItem(""+ tem.getId()+" "+ tem.getNombre() + "");
        }
        
        }
    
    
    
    void limpiarTabla(){
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        while(jTable1.getRowCount()!=0){
            ((DefaultTableModel)jTable1.getModel()).removeRow(0);
        }
    }
    public void LoadCursos(int id){
        List<Curso> cursos = oper.cursosVer(id);
        if(cursos.size()>0){
            Iterator consulta = cursos.iterator();
            
            while(consulta.hasNext()){
                DefaultTableModel tabla = (DefaultTableModel)jTable1.getModel();
                Vector datos = new Vector();
                Curso fila = (Curso)consulta.next();
                datos.add(fila.getId());
                datos.add(fila.getNombre());
                datos.add(fila.getProfesor());
                datos.add(fila.getAula());
                datos.add(fila.getDuracion());
                datos.add(fila.getCargaHoraria());
                datos.add(fila.getCupo());
                tabla.addRow(datos);
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "No hay registros");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Participante aux = null;
        if(buscarMail.getText().equals("")){JOptionPane.showMessageDialog(null, "Debe ingresar un Mail");
        } else {
            aux = oper.buscar(buscarMail.getText());
            if(aux != null){
                nombre.setText(aux.getNombre());
                apellido.setText(aux.getApellido());
                System.out.println(buscarMail.getText());
            } else { 
                nombre.setText("");
                apellido.setText("");
            }
            
        
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tematicasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tematicasItemStateChanged
        // TODO add your handling code here:
        //cambio estado combobox
        if(evt.getStateChange() == ItemEvent.SELECTED)
       {
           if(this.tematicas.getSelectedIndex()>0)
           {
               
            String idString = this.tematicas.getSelectedItem().toString();
            String parte[]= idString.split(" ");
            int id = Integer.parseInt(parte[0]);
            this.tematicas.getSelectedItem().toString();
            limpiarTabla();
            LoadCursos(id);
               
           }
       }
        
        
        
    }//GEN-LAST:event_tematicasItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (aux != null){
            int cantidadCursos = oper.cantidadCursos(aux.getEmail());
            if (cantidadCursos > 2){
             JOptionPane.showMessageDialog(null, "Ya se encuentra inscripto a 3 Cursos","",JOptionPane.ERROR_MESSAGE);
             System.exit(0);
            }
            int filaseleccionada = jTable1.getSelectedRow();
            if (filaseleccionada < 0) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un curso");
            } else {
                    int id_fila = (int)jTable1.getValueAt(filaseleccionada,0);
                    //System.out.println(id_fila);
                    if (oper.cupo(id_fila)){
                            Inscripcion auxInscripcion = new Inscripcion(aux.getEmail(),aux.getEmail(),id_fila,1);
                            int id_generado = oper.guardarinscripcion(auxInscripcion);
                            JOptionPane.showMessageDialog(null, "Estimado "+ aux.getApellido() + ", usted se encuentra inscripto al curso elegido, con el numero de Inscripcion: "+ id_generado);
                            System.exit(0);
                    } else {
                            Inscripcion auxInscripcion = new Inscripcion(aux.getEmail(),aux.getEmail(),id_fila,2);
                            int id_generado = oper.guardarinscripcion(auxInscripcion);
                            JOptionPane.showMessageDialog(null, "Estimado "+ aux.getApellido() + ", usted se encuentra inscripto al curso elegido de Forma Condicional, con el numero de Inscripcion: "+ id_generado);
                            System.exit(0);
                    }
                
                
                          
            }        
        
                    //JOptionPane.showMessageDialog(null, "Estimado"+ aux.getApellido() + ", usted se encuentra inscripto al curso elegido, con el numero de Inscripcion");
                    //if (oper.cupo(2)){
                      //      JOptionPane.showMessageDialog(null, "Debe ingresar un Estudiante");
                    //}
                   //System.out.println(oper.cantidadCursos(aux.getEmail()));
        }else {
        JOptionPane.showMessageDialog(null, "Debe ingresar un Estudiante");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void registradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registradoMouseClicked
        // TODO add your handling code here:
        //desabilitar boton
        jButton1.setEnabled(true);
    }//GEN-LAST:event_registradoMouseClicked

    private void noRegistradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noRegistradoMouseClicked
        // TODO add your handling code here:
        jButton1.setEnabled(false);
    }//GEN-LAST:event_noRegistradoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana_inscripcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JTextField buscarMail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton noRegistrado;
    private javax.swing.JLabel nombre;
    private javax.swing.ButtonGroup opcionRegistrado;
    private javax.swing.JRadioButton registrado;
    private javax.swing.JComboBox<String> tematicas;
    // End of variables declaration//GEN-END:variables
}
