package modelo;
// Generated 25/10/2018 20:20:06 by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String profesor;
     private Integer cargaHoraria;
     private Integer cupo;
     private Integer aula;
     private Integer duracion;
     private int idTematica;

    public Curso() {
    }

	
    public Curso(String nombre, int idTematica) {
        this.nombre = nombre;
        this.idTematica = idTematica;
    }
    public Curso(String nombre, String profesor, Integer cargaHoraria, Integer cupo, Integer aula, Integer duracion, int idTematica) {
       this.nombre = nombre;
       this.profesor = profesor;
       this.cargaHoraria = cargaHoraria;
       this.cupo = cupo;
       this.aula = aula;
       this.duracion = duracion;
       this.idTematica = idTematica;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getProfesor() {
        return profesor;
    }

    public void setProfesor(String profesor) {
        this.profesor = profesor;
    }
    
    public Integer getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(Integer cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public Integer getCupo() {
        return this.cupo;
    }
    
    public void setCupo(Integer cupo) {
        this.cupo = cupo;
    }
    public Integer getAula() {
        return this.aula;
    }
    
    public void setAula(Integer aula) {
        this.aula = aula;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public int getIdTematica() {
        return this.idTematica;
    }
    
    public void setIdTematica(int idTematica) {
        this.idTematica = idTematica;
    }




}


