package modelo;
// Generated 25/10/2018 20:20:06 by Hibernate Tools 4.3.1



/**
 * EstadoInscripcion generated by hbm2java
 */
public class EstadoInscripcion  implements java.io.Serializable {


     private Integer id;
     private String estado;

    public EstadoInscripcion() {
    }

    public EstadoInscripcion(String estado) {
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


