package modelo;
// Generated 25/10/2018 20:20:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private Integer id;
     private Date fechaHora;
     private String mail;
     private String idParticipante;
     private int idCurso;
     private int idEstado;

    public Inscripcion() {
    }

    public Inscripcion(Date fechaHora, String mail, String idParticipante, int idCurso, int idEstado) {
       this.fechaHora = fechaHora;
       this.mail = mail;
       this.idParticipante = idParticipante;
       this.idCurso = idCurso;
       this.idEstado = idEstado;
    }
    public Inscripcion(String mail, String idParticipante, int idCurso, int idEstado) {
       this.mail = mail;
       this.idParticipante = idParticipante;
       this.idCurso = idCurso;
       this.idEstado = idEstado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getIdParticipante() {
        return this.idParticipante;
    }
    
    public void setIdParticipante(String idParticipante) {
        this.idParticipante = idParticipante;
    }
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }




}


