package modelo;
// Generated 26/10/2018 04:05:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Participante generated by hbm2java
 */
public class Participante  implements java.io.Serializable {


     private String email;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private Date fechaNacimiento;
     private String nombreTutor;

    public Participante() {
    }

	
    public Participante(String email, String nombre, String apellido, String nombreTutor) {
        this.email = email;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nombreTutor = nombreTutor;
    }
    public Participante(String email, String nombre, String apellido, String direccion, String telefono, Date fechaNacimiento, String nombreTutor) {
       this.email = email;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.fechaNacimiento = fechaNacimiento;
       this.nombreTutor = nombreTutor;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getNombreTutor() {
        return this.nombreTutor;
    }
    
    public void setNombreTutor(String nombreTutor) {
        this.nombreTutor = nombreTutor;
    }




}


