package modelo;
// Generated 25/10/2018 20:20:06 by Hibernate Tools 4.3.1



/**
 * Tematica generated by hbm2java
 */
public class Tematica  implements java.io.Serializable {


     private Integer id;
     private String nombre;

    public Tematica() {
    }

    public Tematica(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


